# Generated by Django 4.2.27 on 2026-01-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
