# Generated by Django 4.2.27 on 2026-05-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_goal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='tag',
            field=models.CharField(blank=True, default='未分類', max_length=50),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=36)),
                ('reaction_type', models.CharField(choices=[('fire', '🔥'), ('clap', '👏'), ('muscle', '💪')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='tracker.goal')),
            ],
            options={
                'unique_together': {('goal', 'client_id', 'reaction_type')},
            },
        ),
        migrations.CreateModel(
            name='GoalView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=36)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='tracker.goal')),
            ],
            options={
                'unique_together': {('goal', 'client_id')},
            },
        ),
    ]
